Azure-Samples/Cognitive-Speech-TTS

- Samples-Http/NodeJS/TTSService.js
> Fix an error when calculating Content-Length in NodeJS sample

- Samples-Http/NodeJS/TTSService.js
> Use xmlbuilder to build SSML instead of string

- Samples-Http/CSharp/TTSProgram.cs
> Use LINQ to XML to replace handcrafted SSML in C#

- Samples-Http/Java/TTSSample/src/com/microsoft/cognitiveservices/ttssample/TTSService.java
- Samples-Http/Java/TTSSample/src/com/microsoft/cognitiveservices/ttssample/XmlDom.java
> Create SSML through XML DOM in Java

- Samples-Http/Ruby/TTSSample.rb
> Build SSML instead of manipulating strings.

- Samples-Http/Python/TTSSample.py
> Use xml.etree to generate SSML

- Samples-Http/PHP/TTSService.php
> Use DOM to create SSML to speak in PHP

- Samples-Http/NETCore/README.md
- Samples-Http/NETCore/TTSProgram.cs
- Samples-Http/NETCore/TTSProgram.csproj
Simplified .NET Core sample. Removed var and replaced with strongly typed references. Updated README.md.
> Updated sample for .NET Core

- CustomVoice-API/CustomVoice-API/CustomVoice-API.csproj
- CustomVoice-API/CustomVoice-API/CustomVoiceAPI.cs
- CustomVoice-API/CustomVoice-API/Program.cs
- CustomVoice-API/CustomVoice-API/TestData/en-US_small.txt
- CustomVoice-API/CustomVoice-API/VoiceAPI/DTO/VoiceSynthesisDefinition.cs
- CustomVoice-API/CustomVoice-API/VoiceAPI/VoiceAPIHelper.cs
Update sample code of voice synthesis APIs to version V3.0 beta1
> Update sample code of voice synthesis APIs.

- CustomVoice-API/CustomVoice-API/CustomVoiceAPI.cs
- CustomVoice-API/CustomVoice-API/Program.cs
- CustomVoice-API/CustomVoice-API/VoiceAPI/VoiceAPIHelper.cs
add custom voice long audio / audio only data import samples
> Add long audio and audio only dataset API

- CustomVoice-API-Samples/CSharp/CustomVoice-API/CustomVoiceAPI.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/Program.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/VoiceAPI/DTO/Voice.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/VoiceAPI/DTO/VoiceSynthesisDefinition.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/VoiceAPI/VoiceAPIHelper.cs
- CustomVoice-API-Samples/Python/Readme.txt
- CustomVoice-API-Samples/Python/voiceclient.py
1.Support specify audio output format.
2.Add Created/Description field in Voice entity.
> Update client to:

- CustomVoice-API-Samples/Python/Readme.txt
- CustomVoice-API-Samples/Python/voiceclient.py
Add delete and synthese command in python client tool.
> Add delete and synthesis command in python client tool.

- MRCP/ms-common/include/common.h
- MRCP/ms-recog/packages.config
- MRCP/ms-synth/packages.config
- MRCP/ms-synth/src/synthesizer_pool.h
- MRCP/sample-conf/config.json
update sdk version to 1.7.0 and modify for local container
> [MRCP] update sdk version and modify for local container

- MRCP/ms-recog/packages.config
- MRCP/ms-synth/packages.config
- MRCP/sample-conf/config.json
- MRCP/sample-conf/unimrcpclient.xml
update speech sdk version, set 8k as default in the config
> update speech sdk version, set 8k as default in the config

- CustomVoice-API-Samples/CSharp/CustomVoice-API/API/APIHelper.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/API/BatchSynthesis.cs
- CustomVoice-API-Samples/Python/voiceclient.py
Modify the client to change read url from header 'Location' instead of 'Operation-Location'
> Modify the client to change read url from header 'Location' instead of 'Operation-Location'

- CustomVoice-API-Samples/CSharp/CustomVoice-API/API/APIHelper.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/API/API_V3.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/API/BatchSynthesis.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/API/DTO/PaginatedEntities.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/APIArguments.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/APIHandler.cs
- CustomVoice-API-Samples/CSharp/CustomVoice-API/CustomVoice-API.csproj
- CustomVoice-API-Samples/Python/Readme.txt
- CustomVoice-API-Samples/Python/voiceclient.py
Refine CSharp and python sample code to support query voicesynthesis with filters.
> Refine CSharp and python sample code to support query voicesynthesis with filters.

- CustomVoice/script/verbal-statement-all-locales.txt
check in custom voice verbal statement.
> check in custom voice verbal statement.

- LongAudioAPI/CSharp/LongAudioAPISample/.editorconfig
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/LongAudioSynthesisClient.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/LongAudioSynthesisSample.csproj
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/FileLinks.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/PaginatedResults.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/Synthesis.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/SynthesisFile.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/SynthesisProperties.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/Voice.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/VoiceIdentity.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Models/VoiceProperties.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/Program.cs
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioAPISample/enUSScriptSample.txt
- LongAudioAPI/CSharp/LongAudioAPISample/LongAudioSynthesisSample.sln
Add C# sample code of long audio synthesis
> Add CSharp long audio API sample

- GptClientStreaming/CSharp/Program.cs
- GptClientStreaming/CSharp/README.md
- GptClientStreaming/CSharp/TtsClientStreaming.csproj
Add sample code about how to do simple sentence separate for gpt output stream at client side, and call tts for each sentence.
> Gpt client streaming example

- SpokenChat/CSharp/SpokenChat.cs
- SpokenChat/Python/spokenchat.py
- SpokenChat/README.md
Speech services doesn't use an "OpenAI" key. 
Also update the README with explanation of the samples.
> AI services env vars and readme

- CustomVoice/script/English (United States)_en-US/0000000001_0300000050_General.txt
Fix typo is custom voice recording script.
According to https://github.com/Azure-Samples/Cognitive-Speech-TTS/issues/318
fibber-rich => fiber-rich
> Fix typo is custom voice recording script.

- Blog-Samples/202412_ArabicImprovedPronunciation/00014_A.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00014_B.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00014_Hamed.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00015_A.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00015_B.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00015_Hamed.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00028_A.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00028_B.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/00028_Hamed.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/englishword1_baseline.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/englishword1_new.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/englishword2_baseline.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/englishword2_new.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/longsentence_baseline.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/longsentence_new.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/propernoun_baseline.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/propernoun_new.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/shortsentence_baseline.wav
- Blog-Samples/202412_ArabicImprovedPronunciation/shortsentence_new.wav
I am writing a blog for Arabic improved pronunciation.
the demo waves need to be checked in here.
> demo waves for Arabic improved pronunciation

- PronunciationAssessment/CSharp/Console/Program.cs
- PronunciationAssessment/CSharp/Console/PronunciationAssessment.cs
- PronunciationAssessment/CSharp/Console/Recorder.cs
- PronunciationAssessment/CSharp/WPF/MainWindow.xaml.cs
- PronunciationAssessment/CSharp/WPF/ScoreResult.cs
- PronunciationAssessment/Go/README.md
- PronunciationAssessment/Go/go.mod
- PronunciationAssessment/Go/main.go
- PronunciationAssessment/Java/jre/src/com/microsoft/cognitiveservices/pronunciationassessment/Sample.java
- PronunciationAssessment/NodeJS/sample.js
- PronunciationAssessment/Python/sample.py
- PronunciationAssessment/README.md
1. update the REST API parameters
2. adding go examples
> update the REST API parameters

- PronunciationAssessment/NodeJS/package.json
- PronunciationAssessment/NodeJS/sample.js
Update the REST API parameters
> [NodeJS]Update the REST API parameters

- PronunciationAssessment/BrowserJS/application.py
remove "usePipelineVersion" from API parameters
> [BrowserJS][PA]remove "usePipelineVersion" from API parameters

- PronunciationAssessment/BrowserJS/application.py
- PronunciationAssessment/BrowserJS/requirements.txt
- PronunciationAssessment/BrowserJS/static/index.js
- PronunciationAssessment/BrowserJS/templates/index.html
1. Enable prosody assessment
2. Fixed the API request failure issue.
> [PA][BrowserJS]Enable prosody assessment and fixed the API request failure issue.
